### ISSUE TITLE
HAX bug report from preference panel in Grav

### ISSUE THREAD

**Issue by LegendT** [LRNWebComponents/hax-body#174]
URL base: /admin/pages/test

Steps to reproduce:

Download and install Grav v1.6.0-beta.7 - Admin v1.9.0-beta.7
Install plugins - HAX 1.1.2  and Web components loader 1.1.0
move and install the web components into the user/data folder

Issue:
The HAX menu appears with all the sub menus but the page does not get updated. and the HAX editor does not appear on the page.

![screenshot-localhost-8000-2019 01 20-19-33-52](https://user-images.githubusercontent.com/1133438/51444082-b9677180-1cea-11e9-8186-874b616babcc.png)

**Comment by btopro** [comment]
thanks for the repot. please get the 3.x.x releases of both. https://github.com/elmsln/grav-plugin-webcomponents/tree/3.0.1

The stability of HAX and it's integration have improved dramatically since 1.x.x. If there's something I have to do in the publishing of versions to get the latest to register plz let me know (not a grav person natively)

**Comment by btopro** [comment]
also hitting edit in the top left shows edit

**Comment by btopro** [comment]
I just released a 3.0.2 w/ the correct tag so we can at least make sure we're talkinga bout the same things :)

**Comment by LegendT** [comment]
Thanks Bryan,

I've updated to 3.0.2 but I'm still having issues.

I click on the edit and see the Hax menu, but when I choose an option its
not appearing on the page.

Regards
Anthony

**Comment by btopro** [comment]
ok, I was able to replicate this and then when I used the latest releases of projects it resolved (things I have internally). So, I'm going to publish updated releases of hax and then cut a new release of the grav plugin that has an updated package.json to match and then have a try. I'll let you know when the build is published (takes like an hour to run the scripts)

**Comment by LegendT** [comment]
Thanks Bryan you’re a superstar.

Anthony

**Comment by btopro** [comment]
Ok, 3.0.3 of webcomponents plugin is up. get that and hte updated package.json, run through the install routine again and see if that helps

**Comment by btopro** [comment]
https://github.com/elmsln/grav-plugin-webcomponents/blob/3.0.3/CopyThisStuff/package.json

**Comment by btopro** [comment]
also please post future issues to this queue since this is the active one -- https://github.com/elmsln/lrnwebcomponents/issues

If this is still a problem please reopen the issue but over there
